"""Frappe app manifest for UCC Intelligence.

WHY THIS FILE IS NOW IN THE REPOSITORY
It was not, until 2026-08-01, and that is what broke the bench.

`docs/migration/hooks-reference.md` recorded a deliberate decision -- hooks.py
is bench-generated, so it lives on the bench and not here (CLAUDE.md §7:
"the exact scaffold should be generated by the installed Frappe version").
The reasoning was sound and the consequence was not: the repository's
`ucc_intelligence/` directory did not match the bench's app directory, so ANY
mirroring sync that removes extra files at the destination deletes the app's
own manifest. That is exactly what happened, and Frappe cannot load an app
without it -- `bench migrate` and `bench clear-cache` both fail at import.

A file that must exist for the app to load, and that nothing in this repository
declared or checked, was a single flag away from deletion at all times. So it
is version-controlled now. `tools/test_app_loads.py` fails loudly if it, or any
other load-critical file, goes missing again.

WHAT IS AND IS NOT HAND-AUTHORED
The entries below are not recalled -- they are transcribed from
`docs/migration/hooks-reference.md`, which was written when the scheduler and
fixture work was built and records exactly what those modules need. The app
metadata is the standard `bench new-app` set.

`pyproject.toml` is the one scaffold file that IS version-specific (flit vs
setuptools changed between Frappe major versions). If `bench setup requirements`
ever objects to the committed one, replace it with one generated by
`bench new-app` on the real bench and commit that instead.
"""

app_name = "ucc_intelligence"
app_title = "UCC Intelligence"
app_publisher = "United Ceres College Pte Ltd"
app_description = "Institutional analytics, guided answers and controlled AI workflows for UCC SMS"
app_email = "felix@unitedceres.edu.sg"
app_license = "mit"

# ---------------------------------------------------------------------------
# SCHEDULER -- monitoring (docs/migration/hooks-reference.md)
#
# Every entry is gated on `UCC Intelligence Settings.enable_monitoring`, which
# defaults OFF. Registering these starts nothing until monitoring is switched
# on deliberately.
#
# Per-rule cadence lives in monitoring/engine.py's RULE_CADENCE, not here, so
# adding a rule does not mean editing this file.
# ---------------------------------------------------------------------------
scheduler_events = {
	"daily": [
		"ucc_intelligence.monitoring.engine.run_daily",
	],
	"weekly": [
		"ucc_intelligence.monitoring.engine.run_weekly",
	],
	"monthly": [
		# Frappe has no quarterly cron. run_quarterly() self-limits to the
		# first month of a quarter, so registering it monthly is correct and
		# keeps the cadence visible in one place rather than in a custom
		# scheduler.
		"ucc_intelligence.monitoring.engine.run_quarterly",
	],
}

# ---------------------------------------------------------------------------
# FIXTURES -- the controlled-action approval workflow
#
# ucc_intelligence/fixtures/workflow.json is the workflow itself. Without it
# installed, `UCC AI Action Request` records can be created but no transition
# is possible -- which fails safe: nothing can reach Approved, so nothing can
# execute.
# ---------------------------------------------------------------------------
fixtures = [
	{"dt": "Workflow", "filters": [["name", "in", ["UCC AI Action Approval"]]]},
	{"dt": "Workflow State", "filters": [["name", "in", [
		"Draft", "Pending Approval", "Approved", "Rejected", "Executed"]]]},
	{"dt": "Workflow Action Master", "filters": [["name", "in", [
		"Submit for Approval", "Approve", "Reject", "Execute"]]]},
]

# ---------------------------------------------------------------------------
# NOT SET, deliberately
#
# app_include_js -- the Sophia page loads the shared runtime itself, with
#     frappe.require("/assets/ucc_intelligence/js/shared.js", boot). Adding it
#     to every Desk page as well would load it twice for no benefit.
#
# knowledge re-indexing -- "ucc_intelligence.knowledge.ingestion.reindex_stale"
#     is a valid daily entry (hooks-reference.md) but is only worth enabling
#     once real documents are registered. Left out rather than scheduled
#     against an empty index.
# ---------------------------------------------------------------------------
