#!/usr/bin/env python3
"""Generate ucc_intelligence/ucc_intelligence/analytics/criterion_4.py from the
legacy Server Script, using the same verbatim-extraction technique as
tools/generate_criterion_5.py and the five criteria before it.

    python3 tools/generate_criterion_4.py

WHY MECHANICALLY AND NOT BY HAND
3,288 legacy lines, of which ~1,350 are literal configuration: 81 metrics
across 8 sections, 40 management questions, the requirement registry, the
policy registry and the safe-field map. Hand-transcribing that is slow and
silently error-prone, and a single wrong metric id would produce a question
that answers with the wrong number rather than an obvious failure.

THE ONE DIVERGENCE, DECLARED
The legacy `build_admission_intelligence()` at lines 2359-2489 is NOT ported.
Criterion 4's admission block already exists as the Insights-informed
implementation in `analytics/criterion_4_admission.py`, it is live, and Felix
asked for it to keep working. So that range is excluded and the call site at
line 2492 is replaced with a call into that module. Every other line of the
legacy engine is carried through.

tools/test_ucc_intelligence_criterion_4.py re-extracts the same ranges
independently, so a bug in this generator cannot hide a drifted port -- and it
asserts the excluded range is absent as well as that everything else is
present.
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
LEGACY = ROOT / "server-scripts" / "UCC Analytics - Criterion 4.py"
TARGET = ROOT / "ucc_intelligence" / "ucc_intelligence" / "analytics" / "criterion_4.py"

lines = LEGACY.read_text(encoding="utf-8").split("\n")


def extract(start, end):
	return lines[start - 1:end]


def spaces_to_tabs_graceful(block):
	"""Leading 4-space indents to tabs, leaving irregular indentation alone --
	the same per-line-graceful conversion every criterion port has used."""
	out = []
	for line in block:
		if not line.strip():
			out.append("")
			continue
		indent = len(line) - len(line.lstrip(" "))
		out.append("\t" * (indent // 4) + line.lstrip(" ") if indent % 4 == 0 else line)
	return out


def indent_one_more(block):
	return ["\t" + line if line.strip() else "" for line in block]


DOCSTRING = '''"""Criterion 4 (Student Protection and Support Services) analytics engine.

Ported from `server-scripts/UCC Analytics - Criterion 4.py` -- Option A
(verbatim port), the same technique as Criteria 1, 2, 3, 5, 6 and 7.
Generated by `tools/generate_criterion_4.py` and checked by
`tools/test_ucc_intelligence_criterion_4.py`, which re-extracts the same
ranges from the live legacy source and diffs them against this file.

WHAT THIS RESTORED
Until 2026-08-02 this module was `admission_intelligence` and nothing else,
and Criterion 4 was the only criterion with no Management Questions. The
legacy script had them all along -- 40 questions across 8 sections, 81
metrics, the requirement registry -- and an earlier report that they had
"never been built" was wrong, because it looked only at this file and not at
the legacy source. They are all here now.

THE ONE DECLARED DIVERGENCE
`build_admission_intelligence()` (legacy lines 2359-2489) is deliberately NOT
ported. Criterion 4's admission block already exists as the Insights-informed
implementation, and it is live. It moved to
`analytics/criterion_4_admission.py` unchanged, and the legacy call site is
replaced with a call into it:

    admission_intelligence = criterion_4_admission.build_admission_intelligence(
        filters, row_limit)

The legacy function took no arguments and read module-level `filters` and
`row_limit`; the existing one takes them explicitly. That is the whole of the
difference at the call site.

FIVE HELPERS STAY LOCAL, UNLIKE EVERY OTHER PORTED CRITERION
`clean_text`, `lower_text`, `is_truthy`, `to_number` and
`is_permission_error` are defined here rather than imported from
`analytics.engine` / `analytics.contracts`, because Criterion 4's copies are
NOT the shared ones:

  - its `clean_text` is `frappe.utils.cstr(value).strip()`; the shared one is
    `str(value).strip()`
  - its `is_permission_error` does not test for `"403"`; the shared one does
  - `to_number` is not in `analytics.engine` at all

`lower_text` and `is_truthy` are byte-identical to the shared versions, but
both are built on `clean_text` -- importing them would quietly re-bind this
criterion's text handling to the other variant. Fidelity beats tidiness here,
and the divergence is small, named and testable.

`standardise_response_contract` IS imported. Its legacy copy differs from
`analytics/contracts.py` only in the docstring, three extracted constants
(`CONTRACT_VERSION` == "2.1.0", `ARRAY_KEYS`, `MIRROR_KEYS` -- all three
verified equal to the legacy literals) and trailing commas. Behaviourally the
same function, and the same one the other six criteria already use.

CACHES ARE LOCALS OF `run()`, NOT MODULE STATE
`meta_cache`, `resolved_field_cache`, `safe_field_cache`, `filter_cache`,
`source_resolution_cache`, `row_cache`, `row_error_cache`,
`source_field_plan_cache`, `child_field_plan_cache`, `child_row_cache`,
`parent_doc_cache` and `query_stats` are module-level in the legacy script,
where every request is a fresh process. Here they are locals -- the same
treatment Criteria 3, 5, 6 and 7 got, for the same reason: a persistent
worker must never share cached rows or resolved sources between users whose
permissions differ.

PERMISSIONS ARE UNCHANGED FROM THE LEGACY SCRIPT
Every read goes through `frappe.get_list` without `ignore_permissions`, so
ordinary DocType and row permissions apply exactly as they did. Sources a
user cannot read come back as `permission_denied` and are reported, never
converted to a zero.
"""

import frappe

from ucc_intelligence.analytics import criterion_4_admission
from ucc_intelligence.analytics.contracts import standardise_response_contract

ALLOWED_ACTIONS = [
'''

# --- the legacy ranges, in the legacy's own order --------------------------
allowed_actions = extract(60, 62)      # the action strings + closing bracket
guard = extract(63, 64)                # the unsupported-action throw (executable)
static = extract(66, 1421)             # POLICY_REGISTRY .. CHILD_SAFE_FIELDS
helpers = extract(1424, 1457)          # clean_text .. is_permission_error (local, see docstring)
caches = extract(1460, 1478)           # the twelve caches -> locals of run()
engine_a = extract(1480, 2357)         # get_meta .. sort_group_rows
# 2359-2489 build_admission_intelligence -- EXCLUDED, see the docstring
# 2492      admission_intelligence = build_admission_intelligence() -- REPLACED
engine_b = extract(2493, 3002)         # evaluate_requirement .. the summary counters
result_dict = extract(3208, 3259)      # result = {...}
dispatch = extract(3263, 3284)         # action dispatch, after the first contract call

CONTRACT_CALL = ('result = standardise_response_contract(result, "Criterion 4", '
	'"ucc_analytics_criterion_4", action, subcriterion, row_limit)')

ADMISSION_CALL = [
	"# DECLARED DIVERGENCE from the legacy script (line 2492). Two parts:",
	"#",
	"# 1. The legacy build_admission_intelligence() read module-level",
	"#    `filters` and `row_limit`; the Insights-informed implementation",
	"#    takes them explicitly.",
	"# 2. The legacy function opened with `if subcriterion != \"4.1.1\":",
	"#    return {}` -- an internal guard, inside the range this port",
	"#    excludes. The replacement does not carry it, so it is reinstated",
	"#    HERE. Without this line every subcriterion would build the",
	"#    admission block, which is neither what the legacy script did nor",
	"#    what the block means.",
	"#",
	"# See the module docstring.",
	"admission_intelligence = {}",
	'if subcriterion == "4.1.1":',
	"    admission_intelligence = criterion_4_admission.build_admission_intelligence(",
	"        filters, row_limit)",
]

RUN_SIGNATURE = (
	"\n\ndef run(action, subcriterion, filters, metric_id, page, page_size, row_limit):\n"
	'\t"""Criterion 4 analytics: sources, metrics, the 40 management questions,\n'
	'\tthe requirement registry, exceptions, data quality and the admission\n'
	'\tintelligence block."""\n'
)

run_body = list(guard)
run_body += [""] + caches
run_body += [""] + helpers
run_body += [""] + engine_a
run_body += [""] + ADMISSION_CALL
run_body += [""] + engine_b
run_body += [""] + result_dict
run_body += ["", CONTRACT_CALL, ""]
run_body += dispatch
run_body += ["", CONTRACT_CALL, "", "return result"]

parts = [DOCSTRING]
parts.append("\n".join(spaces_to_tabs_graceful(allowed_actions)))
parts.append("\n\n")
# The registries are pure literals, so they stay module-level constants rather
# than being rebuilt on every request -- the same placement Criterion 5 uses.
parts.append("\n".join(static))
parts.append("\n")
parts.append(RUN_SIGNATURE)
parts.append("\n".join(indent_one_more(spaces_to_tabs_graceful(run_body))))
parts.append("\n")

TARGET.write_text("".join(parts), encoding="utf-8")
print("wrote %s (%d lines)" % (TARGET, len(TARGET.read_text(encoding="utf-8").split("\n"))))
