#!/usr/bin/env python3
"""Generate ucc_intelligence/ucc_intelligence/analytics/criterion_5.py from
the legacy Server Script, using the same verbatim-extraction technique the
other five ported criteria used.

Criterion 5 is the largest criterion (3398 legacy lines, 110 metrics across
8 sections, 79 questions) -- transcribing ~2100 lines of literal config by
hand would be slow and, worse, silently error-prone in exactly the places
the investigation flagged as easy to get wrong (the course/module alias
inversion, the `overview` pseudo-subcriterion). Extracting the byte-exact
ranges programmatically removes that whole class of mistake, and
tools/test_ucc_intelligence_criterion_5.py re-extracts the same ranges
independently to prove the committed file still matches.

    python3 tools/generate_criterion_5.py
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
LEGACY = ROOT / "server-scripts" / "UCC Analytics - Criterion 5.py"
TARGET = ROOT / "ucc_intelligence" / "ucc_intelligence" / "analytics" / "criterion_5.py"

lines = LEGACY.read_text(encoding="utf-8").split("\n")


def extract(start, end):
	return lines[start - 1:end]


def spaces_to_tabs_graceful(block):
	"""Convert leading 4-space indents to tabs, leaving irregular indentation
	untouched -- the same per-line-graceful conversion introduced for
	Criterion 2 and used for every criterion since."""
	out = []
	for line in block:
		if not line.strip():
			out.append("")
			continue
		indent = len(line) - len(line.lstrip(" "))
		out.append("\t" * (indent // 4) + line.lstrip(" ") if indent % 4 == 0 else line)
	return out


def indent_one_more(block):
	return ["\t" + line if line.strip() else "" for line in block]


DOCSTRING = '''"""Criterion 5 (Academic Quality: course design, review, planning,
delivery, partnerships, student learning, and assessment) analytics engine.

Ported from `server-scripts/UCC Analytics - Criterion 5.py` -- Option A
(verbatim port), the same technique as Criteria 1, 2, 3, 6 and 7, NOT
Criterion 4's Insights-embed approach. That decision was made by reading
the legacy script in full first: it has no `admission_intelligence`-
equivalent block (zero matches for the term, and no self-contained
KPI/chart-series subsystem anywhere in its 3398 lines). It is the normal
criterion shape -- SOURCE_CANDIDATES -> SAFE_FIELDS -> per-section metric
config -> QUESTION_REGISTRY -> evaluation engine -> response contract --
so it ports like the other five.

Verified by `tools/test_ucc_intelligence_criterion_5.py`, which
re-extracts the same line ranges from the live legacy source and diffs
them against this file. Generated by `tools/generate_criterion_5.py`
rather than hand-transcribed: at 110 metrics across 8 sections this is
the largest criterion, and mechanical extraction removes the risk of a
silent transcription error in exactly the places flagged as easy to get
wrong (see "special cases" below).

**Special cases preserved deliberately** (CLAUDE.md Phase 5 makes
"Criterion 4 and 5 special cases are explicit and tested" an exit
criterion, so each is named here rather than left implicit):

1. **Subcriterion aliases.** `SUBCRITERION_ALIASES = {"5.4": "5.4.1",
   "5.5": "5.5.1"}` -- callers may still pass the old short codes. Every
   registry lookup uses the canonical value; the response reports both,
   plus `legacy_alias_used`. No other criterion has this layer.
2. **The `course`/`module` alias inversion.** `SOURCE_CANDIDATES["course"]
   = ["Program"]` and `SOURCE_CANDIDATES["module"] = ["Course"]` -- the
   alias named `course` resolves to the ERPNext `Program` DocType, and
   `module` resolves to `Course`. This looks like a bug and is not; it is
   UCC's own naming. Copied byte-verbatim precisely so it cannot be
   "corrected" by accident.
3. **The `overview` pseudo-subcriterion.** Unique to Criterion 5: a real,
   selectable `subcriterion` value with its own sources, metrics and
   questions. Not filtered out anywhere.
4. **`question_id` drilldown fallback.** Also unique to Criterion 5: when
   `metric_id` doesn't match, it resolves the metric via the question
   registry instead. The shared `analytics/request.py` doesn't parse
   `question_id` (no other criterion needs it), so `run()` takes it as an
   explicit keyword argument defaulting to `None` and `api.py` reads it
   from the payload separately -- the shared parser is left untouched
   rather than widened for one caller.
5. **Row-limit divergence.** The legacy script defaults `limit` to 500 and
   clamps to 2000; the shared `parse_payload()` (extracted from Criterion
   1) defaults to 2000 and clamps to 5000. Routing Criterion 5 through the
   shared parser unchanged would silently quadruple both. `api.py`'s
   `get_criterion_5()` re-clamps to the legacy 500/2000 after parsing, so
   behaviour is preserved without forking the shared parser.
6. **The exception-metric id list appears twice in the legacy source**
   (once inside `build_custom_metric`'s `attention_count` branch, once as
   `operational_exception_ids`), hand-copied rather than shared. Both
   copies are carried through verbatim -- deduplicating them would be a
   safe change, but it is a change, and this port's job is fidelity.
7. **Five caches, nested not global.** `SOURCE_CACHE`, `META_CACHE`,
   `FIELD_CACHE`, `ROW_CACHE`, `ROW_ERROR_CACHE` are module-level in the
   legacy script, where each request is a fresh process. Here they are
   locals of `run()` -- the same treatment `filter_diagnostics` got in
   Criteria 3/6/7, for the same reason: a persistent worker process must
   not share cached rows or resolved sources across users with different
   permissions.

`clean_text`/`lower_text`/`is_truthy` are imported from
`analytics.engine` -- confirmed byte-identical to this criterion's own
copies (it belongs to the six-of-seven majority; only Criterion 4
diverges). `is_permission_error` and `standardise_response_contract` come
from `analytics.contracts`, same as every other ported criterion.
`to_number` stays local: this criterion's copy is the plain-`float()`
style shared with Criteria 1-3, not Criterion 6/7's currency-stripping
variant.
"""

import frappe

from ucc_intelligence.analytics.contracts import is_permission_error, standardise_response_contract
from ucc_intelligence.analytics.engine import clean_text, is_truthy, lower_text

ALLOWED_ACTIONS = [
'''

allowed_actions = extract(55, 57)          # the action strings + their closing bracket
aliases = extract(61, 61)                  # SUBCRITERION_ALIASES (line 62 derives from it inside run())
static_a = extract(64, 2198)               # POLICY_REGISTRY .. DOCUMENT_ISSUES
static_b = extract(2203, 2213)             # STANDARD_FIELDS + FILTER_FIELD_CANDIDATES
guard = extract(2200, 2201)                # canonical-subcriterion guard (executable)
caches = extract(2215, 2219)               # the five caches -> locals of run()
to_number = extract(2240, 2246)            # local, not one of the shared three
engine_defs = extract(2254, 3001)          # get_meta .. build_question_answer
engine_body = extract(3002, 3087)          # top-level engine execution
result_dict = extract(3294, 3361)          # result = {...}
dispatch = extract(3365, 3394)             # action dispatch (post first contract call)

RUN_SIGNATURE = (
	"\n\ndef run(action, subcriterion, filters, metric_id, page, page_size, row_limit, question_id=None):\n"
	'\t"""Criterion 5 analytics. `question_id` is Criterion 5-only -- see the\n'
	'\tmodule docstring, special case 4."""\n'
	"\trequested_subcriterion = subcriterion\n"
	"\tcanonical_subcriterion = SUBCRITERION_ALIASES.get(requested_subcriterion) or requested_subcriterion\n"
)

run_body_raw = list(guard)
run_body_raw += [""] + caches
run_body_raw += [""] + to_number
run_body_raw += [""] + engine_defs
run_body_raw += [""] + engine_body
run_body_raw += [""] + result_dict
run_body_raw += [
	"",
	'result = standardise_response_contract(result, "Criterion 5", "ucc_analytics_criterion_5", action, canonical_subcriterion, row_limit)',
	"",
]
run_body_raw += dispatch
run_body_raw += [
	"",
	'result = standardise_response_contract(result, "Criterion 5", "ucc_analytics_criterion_5", action, canonical_subcriterion, row_limit)',
	"",
	"return result",
]

parts = [DOCSTRING]
parts.append("\n".join(spaces_to_tabs_graceful(allowed_actions)))
parts.append("\n\n")
parts.append("\n".join(aliases))
parts.append("\n\n")
parts.append("\n".join(static_a))
parts.append("\n\n")
parts.append("\n".join(static_b))
parts.append("\n")
parts.append(RUN_SIGNATURE)
parts.append("\n".join(indent_one_more(spaces_to_tabs_graceful(run_body_raw))))
parts.append("\n")

TARGET.write_text("".join(parts), encoding="utf-8")
print("wrote %s (%d lines)" % (TARGET, len(TARGET.read_text(encoding='utf-8').split(chr(10)))))
